module.exports = {
	apiKey: "7856d350-1fda-45f5-822d-e1a2f3f1acf0",
	clientId: "919e0c1c-76a2-4646-a2fb-7085bbbf3c56",
    configUrl: "http://kretamobile.blob.core.windows.net/configuration/ConfigurationDescriptor.json",
    instituteUrl: "https://kretaglobalmobileapi.ekreta.hu/api/v1/Institute",
    urlTypes: {
        API: "api",
        AUTH: "auth",
        INSTITUTES: "institutes"
    },
	paths: {
        TOKEN: "Token",
		STUDENT: "Student",
		LESSON: "Lesson",
		HOMEWORK: "HaziFeladat",
		TEACHER_HOMEWORK: "TanarHaziFeladat",
		STUDENT_HOMEWORK: "TanuloHaziFeladatLista",
		NEW_HOMEWORK: "CreateTanuloHaziFeladat",
		EXAM: "BejelentettSzamonkeres"
    },
    codenames: [
        "a3xelte",
		"a5xelte",
		"a5y17lte",
		"A6020",
		"a7y17lte",
		"addison",
		"albus",
		"Amber",
		"angler",
		"armani",
		"athene",
		"axon7",
		"bacon",
		"bardock",
		"bardockpro",
		"berkeley",
		"beryllium",
		"bullhead",
		"cancro",
		"capricorn",
		"chagalllte",
		"chagallwifi",
		"chaozu",
		"charlotte",
		"che10",
		"cheeseburger",
		"cherry",
		"cheryl",
		"chiron",
		"clark"
    ]
};
